<template>
  <div>
    <div ref="tabGroup">
      <div>选项卡1</div>
      <div>选项卡2</div>
      <div>选项卡3</div>
      <div>选项卡4</div>
      <div>选项卡5</div>
       <div>选项卡1</div>
      <div>选项卡2</div>
      <div>选项卡3</div>
      <div>选项卡4</div>
      <div>选项卡5</div>
       <div>选项卡1</div>
      <div>选项卡2</div>
      <div>选项卡3</div>
      <div>选项卡4</div>
      <div>选项卡5</div>
       <div>选项卡1</div>
      <div>选项卡2</div>
      <div>选项卡3</div>
      <div>选项卡4</div>
      <div>选项卡5</div>
       <div>选项卡1</div>
      <div>选项卡2</div>
      <div>选项卡3</div>
      <div>选项卡4</div>
      <div>选项卡5</div>
       <div>选项卡1</div>
      <div>选项卡2</div>
      <div>选项卡3</div>
      <div>选项卡4</div>
      <div>选项卡5</div>
       <div>选项卡1</div>
      <div>选项卡2</div>
      <div>选项卡3</div>
      <div>选项卡4</div>
      <div>选项卡5</div>
       <div>选项卡1</div>
      <div>选项卡2</div>
      <div>选项卡3</div>
      <div>选项卡4</div>
      <div>选项卡5</div>
       <div>选项卡1</div>
      <div>选项卡2</div>
      <div>选项卡3</div>
      <div>选项卡4</div>
      <div>选项卡5</div>
       <div>选项卡1</div>
      <div>选项卡2</div>
      <div>选项卡3</div>
      <div>选项卡4</div>
      <div>选项卡5</div>
      <div>选项卡5</div>
       <div>选项卡1</div>
      <div>选项卡2</div>
      <div>选项卡3</div>
      <div>选项卡4</div>
      <div>选项卡5</div>
       <div>选项卡1</div>
      <div>选项卡2</div>
      <div>选项卡3</div>
      <div>选项卡4</div>
      <div>选项卡5</div>
       <div>选项卡1</div>
      <div>选项卡2</div>
      <div>选项卡3</div>
      <div>选项卡4</div>
      <div>选项卡5</div>
       <div>选项卡1</div>
      <div>选项卡2</div>
      <div>选项卡3</div>
      <div>选项卡4</div>
      <div>选项卡5</div>
       <div>选项卡1</div>
      <div>选项卡2</div>
      <div>选项卡3</div>
      <div>选项卡4</div>
      <div>选项卡5</div>
       <div>选项卡1</div>
      <div>选项卡2</div>
      <div>选项卡3</div>
      <div>选项卡4</div>
      <div>选项卡5</div>
       <div>选项卡1</div>
      <div>选项卡2</div>
      <div>选项卡3</div>
      <div>选项卡4</div>
      <div>选项卡5</div>
       <div>选项卡1</div>
      <div>选项卡2</div>
      <div>选项卡3</div>
      <div>选项卡4</div>
      <div>选项卡5</div>
       <div>选项卡1</div>
      <div>选项卡2</div>
      <div>选项卡3</div>
      <div>选项卡4</div>
      <div>选项卡5</div>
    </div>
  </div>
</template>